#ifndef SPRITES_H
#define SPRITES_H

#include "common.h"

enum {
    SPR_TYPE_START = 0u,

    // Cursors
    SPR_TYPE_CURSOR_POINTER = SPR_TYPE_START,
    SPR_TYPE_CURSOR_ERASER,
    SPR_TYPE_CURSOR_HAND,

    // Buttons/indicators
    SPR_TYPE_UNDO_BUTTON,
    SPR_TYPE_DRAW_WIDTH_IND,
    SPR_TYPE_CONFIRM_CHECK,

    SPRITE_CURSOR_COUNT         = ((SPR_TYPE_CURSOR_HAND - SPR_TYPE_CURSOR_POINTER) + 1u),
    SPRITE_UNDO_BUTTON_COUNT    = 1u,
    SPRITE_DRAW_WIDTH_IND_COUNT = 1u,
    SPRITE_CONFIRM_CHECK_COUNT  = 1u
};

enum {
    SPRITE_TILE_MOUSE_START    = 0u,
    SPRITE_TILE_UNDO_BUTTON    = (SPRITE_TILE_MOUSE_START + SPRITE_CURSOR_COUNT),
    SPRITE_TILE_REDO_BUTTON    = (SPRITE_TILE_UNDO_BUTTON),  // Undo, flipped horizontally
    SPRITE_TILE_DRAW_WIDTH_IND = (SPRITE_TILE_UNDO_BUTTON +  SPRITE_UNDO_BUTTON_COUNT),
    SPRITE_TILE_CONFIRM_CHECK  = (SPRITE_TILE_DRAW_WIDTH_IND +  SPRITE_DRAW_WIDTH_IND_COUNT)
};

#define SPR_TYPE_CURSOR_POINTER  (SPR_TYPE_CURSOR_POINTER)
#define SPR_TYPE_CURSOR_ERASER   (SPR_TYPE_CURSOR_ERASER)
#define SPR_TYPE_UNDO_BUTTON     (SPR_TYPE_UNDO_BUTTON)
#define SPR_TYPE_REDO_BUTTON     (SPR_TYPE_REDO_BUTTON)
#define SPR_TYPE_DRAW_WIDTH_IND  (SPR_TYPE_DRAW_WIDTH_IND)
#define SPR_TYPE_CONFIRM_CHECK   (SPR_TYPE_CONFIRM_CHECK)

enum {
    SPRITE_ID_MOUSE_CURSOR = 0u,
    SPRITE_ID_UNDO_BUTTON,
    SPRITE_ID_REDO_BUTTON,
    SPRITE_ID_DRAW_WIDTH_IND,
    SPRITE_ID_CONFIRM_CHECK
};

#define SPRITE_CURSOR_TILE_DATA_START          (sprites_img_tiles + (SPRITE_TILE_MOUSE_START * TILE_SZ_BYTES))
#define SPRITE_UNDO_TILE_DATA_START            (sprites_img_tiles + (SPR_TYPE_UNDO_BUTTON    * TILE_SZ_BYTES))
#define SPRITE_REDO_TILE_DATA_START            (SPRITE_UNDO_TILE_DATA_START)  // Undo button flipped horizontally
#define SPRITE_DRAW_WIDTH_IND_TILE_DATA_START  (sprites_img_tiles + (SPR_TYPE_DRAW_WIDTH_IND * TILE_SZ_BYTES))
#define SPRITE_CONFIRM_CHECK_TILE_DATA_START   (sprites_img_tiles + (SPR_TYPE_CONFIRM_CHECK  * TILE_SZ_BYTES))


#endif // SPRITES_H